version: '2'
services:
  web:
    build: .
    command: [despite, "--dburi=postgres://postgres@db/postgres?sslmode=disable", table-size]
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
     - db
     - metrics
  db:
    image: postgres:9.5
  metrics:
    image: prom/prometheus:0.19.1
    ports:
      - "9090:9090"
